name: "Package ATS"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint_python_code:
    runs-on: ubuntu-latest
    steps:
      - name: lint_python_black
        run:
          black --check ./
      - name: lint_python_flake
        run:
          flake8 ./
  lint_container_file:
    runs-on: self-hosted
    steps:
      - name: lint_docker
        run:
          echo !!!