name: "Package ATS"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint_python_code:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim-bookworm
    steps:
      - name: install_and_setup_poetry
        run: |
          pip install poetry
          poetry --version
      - name: checkout_repo
        uses: actions/checkout@v3
      - name: lint_python_black
        run: |
          poetry run black --check ./
      - name: lint_python_flake
        run: |
          poetry run flake8 ./
  lint_container_file:
    runs-on: self-hosted
    steps:
      - name: lint_docker
        run:
          echo !!!