name: "Package ATS"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint_python_code:
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim-bookworm
    steps:
      - name: lint_python_black
        run: |
          pip install black
          black --check ./
      - name: lint_python_flake
        run: |
          pip install flake8
          flake8 ./
  lint_container_file:
    runs-on: self-hosted
    steps:
      - name: lint_docker
        run:
          echo !!!