name: "Package ATS"
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  lint_python_code:
    name: lint_python_code
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim-bookworm
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
      - name: install_and_configure_poetry
        run: |
          pip install poetry
          poetry --version
          poetry config virtualenvs.in-project true
      - name: install_python_package
        run: |
          poetry install
      - name: lint_python_bandit
        run: |
          poetry run bandit -c pyproject.toml -r .
      - name: lint_python_black
        run: |
          poetry run black --check ./
      - name: lint_python_flake
        run: |
          poetry run flake8 ./
      - name: lint_python_mypy
        run: |
          echo !!lint_python_mypy
      - name: lint_python_pylint
        run: |
          echo !!lint_python_pylint
      - name: lint_python_pyright
        run: |
          echo !!lint_python_pyright
      - name: lint_python_ruff
        run: |
          poetry run ruff check --config pyproject.toml ./
      - name: lint_documentation_pydocstyle
        run:
          echo !!lint_documentation_pydocstyle
  lint_container_file:
    name: lint_container_file
    runs-on: ubuntu-latest
    steps:
      - name: checkout_repo
        uses: actions/checkout@v3
      - name: lint_docker
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./docker/Dockerfile
  build_python_package:
    name: build_python_package
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim-bookworm
    needs: [lint_python_code, lint_container_file]
    steps:
      - name: build_package
        run:
          export $APP_VERSION=$(poetry version --short)
          poetry version $APP_VERSION
          poetry repositories.github "http://aaa"
          poetry config virtualenvs.in-project true
          poetry build
      - name: publish_package
        run:
          echo publish_package
  build_container_image:
    name: build_container_image
    needs: [build_python_package]
    runs-on: ubuntu-latest
    container:
      image: python:3.11-slim-bookworm
    steps:
      - name: build_image
        run:
          echo build container image!